server:
  servlet:
    context-path: ${server.servlet.context-path}
  port: ${server.port}
spring:
  profiles:
    active: local
  datasource:
     driver-class-name: org.postgresql.Driver
     url: ${spring.datasource.url}
     username: ${spring.datasource.username}
     password: ${spring.datasource.password}
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,beans,conditions
springdoc:
  api-docs:
    enabled: true # 預設的
    path: /api-docs # API 文件的路徑，預設的
  swagger-ui:
    enabled: true # 預設的
    path: /swagger-ui.html # Swagger UI 界面的路徑，預設的
mybatis:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.zodiac
  configuration:
    map-underscore-to-camel-case: true
    log-impl: ${mybatis.configuration.log-impl}


